Repository hhu-propra2/abschlussprojekt-big_f_for_auas, pull requests merged in 2020-03, with the labels that each got.

#1 add arc42 template
  documentation/arc42-template-EN.md
  documentation/images/05_building_blocks-EN.png
  documentation/images/08-Crosscutting-Concepts-Structure-EN.png
  documentation/images/arc42-logo.png
Labels: documentation

#13 Protokoll Plenum 4.3.
  documentation/plenum/4.3.md
  documentation/plenum/4.3_User_Story_Abstimmung.jpeg
  documentation/plenum/4.3_User_Story_Terminfindung.jpeg
  documentation/plenum/4.3_User_Story_Veröffentlichung.jpeg
Labels: documentation

#18 Documentation
  documentation/arc42-template-DE.md
  documentation/arc42-template-EN.md
Labels: documentation

#87 Mapping von Error-Nachrichten auf bestimmte Felder funktioniert jetzt
  src/main/java/mops/adapters/datepolladapter/DatePollAdapter.java
  src/main/java/mops/adapters/datepolladapter/dtos/ConfigDto.java
  src/main/java/mops/adapters/datepolladapter/dtos/GeneralDto.java
  src/main/java/mops/adapters/datepolladapter/dtos/MetaInfDto.java
  src/main/java/mops/domain/models/FieldErrorNames.java
  src/main/resources/errormappings/datepollmappings.properties
  src/main/resources/messages/flow-messages.properties
  src/main/resources/messages/flow-messages_DE.properties
  src/main/resources/templates/fragments/general.html
  src/main/resources/templates/fragments/nameSettings.html
Labels: Anspruchsvoll

#92 Bug in Validation: removeErrors(PollFields fieldTyp) funktioniert nicht
  src/main/java/mops/domain/models/Validation.java
Labels: bug

#99 reject datePoll publish, if link is already taken
  src/main/java/mops/application/services/DatePollSyndicationService.java
Labels: bug

#89 Immer alle drei Checks ausführen
  .github/workflows/build.yml
Labels: enhancement

#118 Bugfix: Webflow datepoll confirmation
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/EntriesAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/EntryAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/EntriesDto.java
  src/main/resources/flows/errormappings/datepollmappings.properties
  src/main/resources/flows/messages/flow-messages.properties
  src/main/resources/flows/templates/fragments/datePollEntries.html
Labels: bug

#124 Wir haben jetzt einen Dateiupload
  documentation/fileupload/beispiel.json
  documentation/fileupload/beispiel_invalid.json
  documentation/fileupload/fileupload.md
  src/main/java/mops/infrastructure/adapters/webflow/ErrorMessageHelper.java
  src/main/java/mops/infrastructure/adapters/webflow/PublicationAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/WebFlowAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/BuilderService.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/ConfigAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/EntriesAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/MetaInfAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/UploadService.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/builderdtos/Entries.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/converters/ConfigConverter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/converters/MetaInfConverter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/ConfigDto.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/DatePollDto.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/EntriesDto.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/EntryDto.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/MetaInfDto.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/webflowdtos/UploadDto.java
  src/main/java/mops/infrastructure/config/MvcConfig.java
  src/main/resources/application.properties
  src/main/resources/flows/definitions/scheduling/scheduling-flow.xml
  src/main/resources/flows/messages/flow-messages.properties
  src/main/resources/flows/templates/fragments/confirmation.html
  src/main/resources/flows/templates/fragments/fileUpload.html
  src/main/resources/flows/templates/fragments/metaInf.html
  src/main/resources/flows/templates/fragments/publication.html
  src/main/resources/flows/templates/fragments/settings.html
  src/main/resources/flows/templates/scheduling/fileUpload.html
Labels: enhancement

#128 dropWhile ersetzt
  src/main/java/mops/infrastructure/adapters/webflow/PublicationAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/EntriesAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/datepoll/UploadService.java
Labels: bug

#137 Gruppensynchronisation funktioniert jetzt
  build.gradle
  documentation/groupsync/Swagger UI.html
  documentation/groupsync/Swagger UI_files/springfox.css
  documentation/groupsync/Swagger UI_files/springfox.js
  documentation/groupsync/Swagger UI_files/swagger-ui-bundle.js
  documentation/groupsync/Swagger UI_files/swagger-ui-standalone-preset.js
  documentation/groupsync/Swagger UI_files/swagger-ui.css
  src/main/java/mops/DummyDataCommandLineRunner.java
  src/main/java/mops/domain/models/group/Group.java
  src/main/java/mops/infrastructure/config/GroupSyncConfig.java
  src/main/java/mops/infrastructure/database/daos/GroupDao.java
  src/main/java/mops/infrastructure/database/daos/translator/DaoOfModelUtil.java
  src/main/java/mops/infrastructure/database/daos/translator/ModelOfDaoUtil.java
  src/main/java/mops/infrastructure/groupsync/GroupSyncService.java
  src/main/java/mops/infrastructure/groupsync/GroupSyncValidator.java
  src/main/java/mops/infrastructure/groupsync/GroupSyncWebclient.java
  src/main/java/mops/infrastructure/groupsync/dto/GroupDto.java
  src/main/java/mops/infrastructure/groupsync/dto/GroupSyncInputDto.java
  src/main/java/mops/infrastructure/groupsync/dto/GroupSyncValidDto.java
  src/main/java/mops/infrastructure/groupsync/dto/UserDto.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application.properties
  src/test/java/mops/database/DatabaseDatePollIntegrityTest.java
  src/test/java/mops/database/DatabaseQuestionPollIntegrityTest.java
  src/test/java/mops/database/DatePollVotingProcedure.java
  src/test/java/mops/database/DatePollsFromUser.java
  src/test/java/mops/database/FindDatePollEntryTests.java
  src/test/java/mops/database/UserVotesForDatePollTest.java
Labels: enhancement

#144 Gruppensuche funktioniert jetzt im DatePoll Flow
  src/main/java/mops/DummyDataCommandLineRunner.java
  src/main/java/mops/application/services/GroupService.java
  src/main/java/mops/application/services/implementation/GroupServiceImpl.java
  src/main/java/mops/domain/models/group/Group.java
  src/main/java/mops/domain/models/group/GroupMetaInf.java
  src/main/java/mops/domain/models/group/GroupVisibility.java
  src/main/java/mops/domain/repositories/DomainGroupRepository.java
  src/main/java/mops/domain/repositories/GroupRepository.java
  src/main/java/mops/infrastructure/adapters/webflow/PublicationAdapter.java
  src/main/java/mops/infrastructure/adapters/webflow/dtos/GroupSuggestionDto.java
  src/main/java/mops/infrastructure/adapters/webflow/dtos/PublicationDto.java
  src/main/java/mops/infrastructure/config/GroupSyncConfig.java
  src/main/java/mops/infrastructure/database/daos/GroupDao.java
  src/main/java/mops/infrastructure/database/daos/translator/DaoOfModelUtil.java
  src/main/java/mops/infrastructure/database/daos/translator/ModelOfDaoUtil.java
  src/main/java/mops/infrastructure/database/repositories/DatePollRepositoryImpl.java
  src/main/java/mops/infrastructure/database/repositories/GroupRepositoryImpl.java
  src/main/java/mops/infrastructure/database/repositories/interfaces/GroupJpaRepository.java
  src/main/java/mops/infrastructure/groupsync/GroupSyncService.java
  src/main/java/mops/infrastructure/groupsync/GroupSyncValidator.java
  src/main/java/mops/infrastructure/rest/GroupRepositoryImpl.java
  src/main/resources/flows/definitions/scheduling/scheduling-flow.xml
  src/main/resources/flows/templates/fragments/publication.html
  src/main/resources/flows/templates/scheduling/publication.html
  src/main/resources/static/jquery-ui/AUTHORS.txt
  src/main/resources/static/jquery-ui/LICENSE.txt
  src/main/resources/static/jquery-ui/images/ui-icons_444444_256x240.png
  src/main/resources/static/jquery-ui/images/ui-icons_555555_256x240.png
  src/main/resources/static/jquery-ui/images/ui-icons_777620_256x240.png
  src/main/resources/static/jquery-ui/images/ui-icons_777777_256x240.png
  src/main/resources/static/jquery-ui/images/ui-icons_cc0000_256x240.png
  src/main/resources/static/jquery-ui/images/ui-icons_ffffff_256x240.png
  src/main/resources/static/jquery-ui/jquery-ui.css
  src/main/resources/static/jquery-ui/jquery-ui.js
  src/main/resources/static/jquery-ui/jquery-ui.min.css
  src/main/resources/static/jquery-ui/jquery-ui.min.js
  src/main/resources/static/jquery-ui/jquery-ui.structure.css
  src/main/resources/static/jquery-ui/jquery-ui.structure.min.css
  src/main/resources/static/jquery-ui/jquery-ui.theme.css
  src/main/resources/static/jquery-ui/jquery-ui.theme.min.css
  src/main/resources/static/jquery-ui/package.json
  src/test/java/mops/database/DatabaseDatePollIntegrityTest.java
  src/test/java/mops/database/DatabaseQuestionPollIntegrityTest.java
  src/test/java/mops/database/DatePollVotingProcedure.java
  src/test/java/mops/database/DatePollsFromUser.java
  src/test/java/mops/database/FindDatePollEntryTests.java
  src/test/java/mops/database/LoadingDatePollWithBallots.java
  src/test/java/mops/database/UserVotesForDatePollTest.java
Labels: enhancement
